# Generated by Django 5.0 on 2024-01-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulaire', '0008_alter_task_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofspeech',
            name='abbr',
            field=models.CharField(default='n', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
