# Generated by Django 5.0 on 2024-01-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulaire', '0009_partofspeech_abbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partofspeech',
            name='abbr',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
