# Generated by Django 5.0 on 2023-12-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutch',
            name='lexeme',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='russian',
            name='lexeme',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
