# Generated by Django 5.0 on 2023-12-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulaire', '0002_alter_dutch_lexeme_alter_russian_lexeme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dutch',
            new_name='DutchWord',
        ),
        migrations.RenameModel(
            old_name='Russian',
            new_name='RussianWord',
        ),
    ]
