# Generated by Django 5.0 on 2023-12-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulaire', '0003_rename_dutch_dutchword_rename_russian_russianword'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'parts of speech',
            },
        ),
        migrations.AddField(
            model_name='dutchword',
            name='part_of_speech',
            field=models.ManyToManyField(to='Vocabulaire.partofspeech'),
        ),
        migrations.AddField(
            model_name='russianword',
            name='part_of_speech',
            field=models.ManyToManyField(to='Vocabulaire.partofspeech'),
        ),
    ]
