# Generated by Django 5.0 on 2023-12-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulaire', '0006_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
        migrations.AddField(
            model_name='homework',
            name='done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
