# Generated by Django 5.0 on 2023-12-30 21:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulaire', '0007_remove_task_done_homework_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
