# Generated by Django 5.0 on 2024-02-14 12:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulaire', '0011_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
