# Generated by Django 5.0 on 2024-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulaire', '0013_alter_homework_created_alter_update_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
