# Generated by Django 5.0 on 2024-02-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vocabulaire', '0014_homework_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
